
//import { Geist, Geist_Mono } from "next/font/google";
import BodyWrapper from "@/components/BodyWrapper";
import "./globals.css";
import Footer from "@/components/Footer";


import { Nunito } from 'next/font/google';

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-nunito',
});
export const metadata = {
  title: "Dr. Jagan Mohan Varakala | Top Peadiatrician",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <BodyWrapper> 
        <div className="home">
          {children}
          </div>
        </BodyWrapper>
        <Footer />
      </body>
    </html>
  );
}
